### PR TITLE
pfq-gen: add a poisson process traffic pattern

### PR DESCRIPTION
**Pull request by emmericp**
This adds the option "-p" to pfq-gen to generate inter-packet gaps based on an exponential distribution.

### CODE REVIEW

**Comment by awgn** [comment]
Thanks for submitting the patch guys. 

However, I have a doubt. The pkt_time is not possible to compute, unless the speed of the link is known. The formula used, indeed, assumes that the link is 10G (e.g. on a 40G we need to divide it by 4).

Why don't we simply omit this? Have you already performed some tests without pkt_time (= 0) ? 

I think It's not a problem if the inter-departure time is less than the time required for Tx a packet + IPG. It's physically impossible to fix this, but at least the packets that follow will takes this into account.

The system should be able to produce the correct requested rate on average.

In addition, consider to disable the bulk transmission (xmit_batch_len = 0) to obtain a greater precision.
 
Regards,
N.

**Comment by emmericp** [comment]
We prefer to control the distribution of the inter-packet gaps instead of the inter-departure times because it allows us to compare the resulting distribution (which we plan to measure with a NetFPGA) with the expected analytical model. We can then use a metric like "lambda == avg == stddev?" to quantify the precision/accuracy of a packet generator/timing control measure.

This doesn't really work when we just ignore the packet length as this skews the distribution during sending: there would be too many inter-packet gaps of 0.

Is there a simple way to get this 0.8ns constant from the speed of the used device(s)?


I just ran some initial experiments with an Intel X540 connected to a poor man's DAQ (an Intel 82580 which does reasonble hardware timestamping at 1 Gbit/s). Here are the generated distributions on a log scale at two rates:

0.145 Mpps (~10% of line rate): https://www.dropbox.com/s/972oidypsnlz27j/pfq-p-144.8.pdf?dl=1
0.724 Mpps (~50% of line rate): https://www.dropbox.com/s/krz03wc23byzkpw/pfq-p-724.pdf?dl=1

The second one looks like a huge blob because each other bucket is hit more often and I just plotted the histogram as a line. This might just be an artefact of our "DAQ"

Used settings:
	pfq_options  = [ "capture_incoming=0", "xmit_batch_len=1", "skb_pool_size=1024" ],

(which I assume you meant as len = 0 is rejected as invalid)

I waited for 20 seconds after starting pfq-gen before starting to capture and then captured a few million packets.

**Comment by awgn** [comment]
I understand your problem...

The 0.8ns is basically what you get when multiply the length of the packet by 8/10E9 (8 (bit) / Speed Link).

Hence if you want to make it portable you can either add an additional parameter (in case of poisson generation) that specify the speed in gigabit/sec or you have to run some magic ethtool command in order to detect the speed on your own. 

In both case you need a factor 1, 10, 40 (for 1G, 10G and 40).

In practice, if you have an integer:

int speed_gbit = 40;

then the packet_time should be:

auto pkt_time = std::nanoseconds((len+24) * 8 / speed_gbit );

Yes, xmit_batch_len =1 is right for your purposes.

As far as I remember the distribution we obtained some years ago was more accurate, especially for such slow rates. You could also try the application pfq-histogram which aims at producing the distribution of inter arrival of packets.

It's long time I don't use it, it could be buggy!

N.

**Comment by awgn** [comment]
Hi guys,

I have just updated (in the experimental branch) the pkt_time estimation using ethtool to detect the speed link. It seems to work properly. Let me know if you encounter additional problems.

I'll release and merge this into master tomorrow morning.

Regards,
N.

**Comment by emmericp** [comment]
Seems to work, thanks.
But you broke the calculation of the inter-packet gap, see pull request #17.


Regarding the precision: we'll test that properly with a netfpga soon and share the results with you.

I suspect that the lower-than-expected precision could be caused by Linux kernel 3.19.
We've had some issues with DCA (or Intel DDIO or whatever DPDK is using) with this kernel before, it simply didn't work and the NIC had to get each packet from the main memory which would be really bad for the precision.

**Comment by awgn** [comment]
Perfect! Thank you guys for the support!

**Pull request merged**
